theme: jekyll-theme-dinky

integration_spreadsheet_key: 2PACX-1vTj4kFBNEVrBGhcPxMvdy4rR327K5H5xpZsj1GhhgPdcIk8Wv2YE5ysqxmXFXEMZFQtq1as1g0zYYON

github_user: jempaynation
github_repo: jempaynation.github.io
